version: "3.8"
services:
  web1:
    image: nginx
    volumes:
      - ./config/web1.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - DOMAIN_NAME:"darksunmac"
      - REDIRECT_IP:"10.0.0.122"
